# permissions for end users to edit mysqlhaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlhacluster-editor-role
rules:
- apiGroups:
  - mysql.tongtech.com
  resources:
  - mysqlhaclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mysql.tongtech.com
  resources:
  - mysqlhaclusters/status
  verbs:
  - get
