# permissions for end users to view mysqlhaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlhacluster-viewer-role
rules:
- apiGroups:
  - mysql.tongtech.com
  resources:
  - mysqlhaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.tongtech.com
  resources:
  - mysqlhaclusters/status
  verbs:
  - get
